suppressWarnings(suppressMessages({
    library(shiny)
    library(shinyBS)
    library(shinycssloaders)
    library(shinyWidgets)
    library(shinythemes)
    library(shinyjs)
    library(htmlwidgets)
    library(readr)
    library(dplyr)
    library(reshape2)
    library(lubridate)
    library(sf)
    library(leaflet)
    library(leaflet.esri)
    library(billboarder)
    library(DT)
    library(waiter)
}))

# ui modules
source('modules/ui/action_button_css.R')
source('modules/ui/inline_block_css.R')
source('modules/ui/input_ui.R')
source('modules/ui/navbar_page.R')
source('modules/ui/metric_ui.R')
source('modules/ui/chart_ui.R')

# server modules
source('modules/server/render_timeseries.R')
source('modules/server/render_barchart.R')
source('modules/server/render_donut.R')
source('modules/server/render_table.R')
